Metrics/AbcSize:
  Enabled: False
  Max: 25
Metrics/BlockLength:
  Enabled: False
  Max: 30
Metrics/ClassLength:
  Max: 150
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  CountComments: false
  Max: 20
Metrics/PerceivedComplexity:
  Max: 8
EndOfLine:
  Enabled: False
Bundle/OrderedGems:
  Enabled: False
