language: ruby
matrix:
  include:
    - rvm: 2.1
    - rvm: 2.2
    - rvm: 2.3.1
    - rvm: ruby-head
    - rvm: jruby-9.0.1.0
      env: JRUBY_OPTS='--debug'
    - rvm: rbx-2
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
  fast_finish: true
cache: bundler
before_script: bundle update
script:
  - bundle exec rspec
  - bundle exec codeclimate-test-reporter
  - bundle exec rubocop
addons:
  code_climate:
    repo_token: e94010bac8346a86f5cdc7e809b428e41a533eca5f0459d93e8455e7d873dde6
